dist: bionic
language: node_js
node_js: lts/*

if: tag IS present

script: yarn tsc

deploy:
  provider: npm
  email: kidonng@gmail.com
  api_key: $npm_token
  skip_cleanup: true
  on:
    tags: true
